name: Bug report
description: Report something that isn't working
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 123 / Firefox 124 / etc
  - type: textarea
    id: logs
    attributes:
      label: Console logs (if any)
      render: shell
